version: '3'

services:

  launcher:
    image: eclipse/che
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock 
      - ./user:/data
    network_mode: host
    container_name: launcher
    hostname: launcher
    restart: always
    command: start --follow
    logging:
      driver: json-file
      options:
        max-size: "20k"

